spring:
  application:
    name: "library"
  datasource:
    url: jdbc:h2:mem:db
    username: "sa"
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

server:
  port: 8081
