server:
  port: 8888

spring:
  application:
    name: "configserver"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/PatrykKukula/config-server-for-online-shop.git"
          force-pull: true
          clone-on-start: true
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true